apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: ingress-basic
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mohamed.benighil@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux


#apiVersion: cert-manager.io/v1
#kind: ClusterIssuer
#metadata:
#  name: letsencrypt
#spec:
#  acme:
#    email: "mohamed.benighil07@gmail.com"
#    #server: https://acme-staging-v02.api.letsencrypt.org/directory
#    server: https://acme-v02.api.letsencrypt.org/directory
#    privateKeySecretRef:
#      name: letsencrypt
#    solvers:
#    - selector: {}
#      http01:
#        ingress:
#          class: nginx
#apiVersion: cert-manager.io/v1
#kind: ClusterIssuer
#metadata:
#  name: letsencrypt
#spec:
#  acme:
#    server: https://acme-v02.api.letsencrypt.org/directory
#    email: mohamed.benighil07@gmail.com
#    privateKeySecretRef:
#      name: letsencrypt
#    solvers:
#    - http01:
#        ingress:
#          class: nginx
##apiVersion: cert-manager.io/v1
##kind: ClusterIssuer
##metadata:
##  name: letsencrypt-staging
##spec:
#  acme:
#    # You must replace this email address with your own.
#    # Let's Encrypt will use this to contact you about expiring
#    # certificates, and issues related to your account.
#    email: mohamed.benighil07@gmail.com
#    server: https://acme-staging-v02.api.letsencrypt.org/directory
#    privateKeySecretRef:
#      # Secret resource that will be used to store the account's private key.
#      name: letsencrypt-staging
#    # Add a single challenge solver, HTTP01 using nginx
#    solvers:
#    - http01:
#        ingress:
#          class: nginx
#




#apiVersion: cert-manager.io/v1
#kind: ClusterIssuer
#metadata:
#  name: letsencrypt
#spec:
#  acme:
#    # You must replace this email address with your own.
#    # Let's Encrypt will use this to contact you about expiring
#    # certificates, and issues related to your account.
#    email: mohamed.benighil07@gmail.com
#    #server: https://acme-staging-v02.api.letsencrypt.org/directory
#    server: https://acme-v02.api.letsencrypt.org/directory
#    privateKeySecretRef:
#      # Secret resource that will be used to store the account's private key.
#      #name: example-issuer-account-key
#      name: letsencrypt
#    # Add a single challenge solver, HTTP01 using nginx
#    solvers:
#    - http01:
#        ingress:
#          class: nginx
#
#
#apiVersion: cert-manager.io/v1alpha2
#kind: ClusterIssuer
#metadata:
#  name: letsencrypt
#spec:
#  acme:
#    server: https://acme-v02.api.letsencrypt.org/directory
#    email: dkalyanreddy@gmail.com
#    privateKeySecretRef:
#      name: letsencrypt
#    solvers:
#      - http01:
#          ingress:
#            class: nginx